
version: '3'
services:
  crud-backend:
    container_name: csharp-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - crud-database
    environment:
      ConnectionStrings__DefaultConnection: "Host=crud-database;Database=postgres;Username=postgres;Password=postgres"
  crud-database:
    container_name: crud-database
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}